import Ffpb from '../../public/assets/speakers-pics/Remy-Ozcan-FFPB/FFPB.jpg'
import Remy from '../../public/assets/speakers-pics/Remy-Ozcan-FFPB/Remy-Ozcan-FFPB.jpeg'

import Barreau from '../../public/assets/speakers-pics/Sabine-Van-Haecke-Lepic-Barreau-de-Paris/Barreau-de-Paris.svg'
import Sabine from '../../public/assets/speakers-pics/Sabine-Van-Haecke-Lepic-Barreau-de-Paris/Sabine-Van-Haecke-Lepic-Barreau-de-Paris.jpeg'

// import SpeakerDescription from '@/components/speaker-description/speaker-description.component'

export const day1Program = [
  {
    heading: 'program main stage',
    id: 'day-1-1',
    title: 'Day 1 - 18th July - Understanding and Fostering Blockchain Adoption',
    showContent: false,
    items: [
      {
        id: 'item-1',
        time: '11:00 - 11:20',
        title: 'Opening Keynote',
        speakers: [],
      },
      {
        type: 'Panel',
        id: 'item-2',
        time: '11:20 - 12:05',
        title: 'The Emerging Web3: How Blockchain is Transforming the Internet',
        speakers: [],
      },
      {
        type: 'Workshop',
        id: 'item-3',
        time: '12:05 - 12:30',
        title: 'Fostering Mass Adoption of Blockchain',
        speakers: [],
      },
      {
        type: 'Panel',
        id: 'item-4',
        time: '12:30 - 13:20',
        title: 'Bridging the Gap: How to Drive Blockchain Adoption Among the General Public',
        speakers: [],
      },
      {
        id: 'item-5',
        time: '13:20 - 14:10',
        title: 'LUNCH',
      },
      {
        id: 'item-6',
        time: '14:10 - 14:30',
        title: 'FFPB initiatives with institution and corporate',
        speakers: [],
      },
      {
        type: 'Panel',
        id: 'item-7',
        time: '14:30 - 15:15',
        title: 'DAO : new paradigm for modern business approach',
        speakers: [],
      },
      {
        id: 'item-8',
        time: '15:15 - 15:30',
        title: '"How to avoid chaos” a story between Humans & Blockchain',
        speakers: [],
      },
      {
        type: 'Panel',
        id: 'item-9',
        time: '15:30 - 16:20',
        title: '"How to avoid Chaos" the theory part',
        speakers: [],
      },
      {
        id: 'item-10',
        time: '16:20 - 16:40',
        title: 'BREAK',
      },
      {
        type: 'Panel',
        id: 'item-11',
        time: '16:40 - 17:30',
        title: '"How to avoid Chaos" use-cases part',
        speakers: [],
      },
      {
        id: 'item-12',
        time: '17:30 - 18:00',
        title: 'Closing Keynote',
        speakers: [],
      },
    ],
  },
  {
    heading: 'polkadot stage',
    id: 'day-1-2',
    title: 'program for 18.07',
    showContent: false,
    items: [
      {
        id: 'item-1',
        time: '11:30 - 11:45',
        title: 'Privacy in DeFi with ZK',
        speakers: [],
      },
      {
        id: 'item-2',
        time: '11:45 - 12:00',
        title: 'DePin.. bridging the gap between the real world and crypto',
        speakers: [],
      },
      {
        id: 'item-3',
        time: '12:00 - 12:15',
        title: 'Protecting your tokens with Logion',
        speakers: [],
      },
      {
        id: 'item-4',
        time: '12:15 - 12:30',
        title: 'Light Clients: On the Critical Path to Decentralisation',
        speakers: [],
      },
      {
        id: 'item-5',
        time: '12:30 - 12:45',
        title: 'Safe, fun and efficient: smart contracts in ink!.',
        speakers: [],
      },
      {
        id: 'item-6',
        time: '12:45 - 13:00',
        title: 'Data Ownership with Decentralized Storage',
        speakers: [],
      },
      {
        id: 'item-7',
        time: '13:00 - 14:00',
        title: 'LUNCH',
      },
      {
        id: 'item-8',
        time: '14:00 - 14:15',
        title: 'Remote Execution Using XCM',
        speakers: [],
      },
      {
        id: 'item-9',
        time: '14:15 - 14:30',
        title: "How NFTs can change your user's entire experience",
        speakers: [],
      },
      {
        id: 'item-10',
        time: '14:30 - 14:45',
        title: 'Phat Contract. Smart Contracts. Now Smarter',
        speakers: [],
      },
      {
        id: 'item-11',
        time: '14:45 - 15:00',
        title: 'TBD',
        speakers: [],
      },
      {
        id: 'item-12',
        time: '15:00 - 15:15',
        title: 'Developing better, faster cross-chain dApps with data indexing',
        speakers: [],
      },
      {
        id: 'item-13',
        time: '15:15 - 15:30',
        title: 'Building Smarter Solutions with Vara',
        speakers: [],
      },
      {
        id: 'item-14',
        time: '15:30 - 15:45',
        title: 'The interoperable future: How SORA Card brings tradfi to substrate DeFi',
        speakers: [],
      },
      {
        id: 'item-15',
        time: '15:45 - 16:00',
        title: 'Real World Assets and Token Economy on Polkadot',
        speakers: [],
      },
      {
        id: 'item-16',
        time: '16:00 - 16:15',
        title: 'Decentralized Storage Infrastructure / Scalability',
        speakers: [],
      },
      {
        id: 'item-17',
        time: '16:15 - 16:30',
        title: 'TBD',
        speakers: [],
      },
    ],
  },
  {
    heading: 'Rooftop',
    id: 'day-1-3',
    title: 'Day 1 - 18th July',
    showContent: false,
    items: [
      {
        type: 'Networking session',
        id: 'item-1',
        time: '18:00 - 20:30',
        title: 'Food and Drinks"',
        speakers: [],
      },
    ],
  },
]

export const day2Program = [
  {
    heading: 'Program main stage',
    id: 'day-2-1',
    title: 'Day 2 - 19th July - Considering blockchain through concrete projects',
    showContent: false,
    items: [
      {
        id: 'item-1',
        time: '10:45 - 11:15',
        title: 'The dual Polkadot VC Model',
        speakers: [],
      },
      {
        type: 'Panel',
        id: 'item-2',
        time: '11:15 - 12:00',
        title: 'VC panel',
        speakers: [],
      },
      {
        id: 'item-3',
        time: '12:00 - 12:30',
        title: 'gaming / Sandbox',
        speakers: [],
      },
      {
        id: 'item-4',
        time: '12:30 - 13:00',
        title: 'Web3 in Japan',
        speakers: [],
      },
      {
        id: 'item-5',
        time: '13:00 - 13:30',
        title: 'gaming / EverdreamSoft',
        speakers: [],
      },
      {
        id: 'item-6',
        time: '13:30 - 14:15',
        title: 'LUNCH',
      },
      {
        type: 'Workshop',
        id: 'item-7',
        time: '14:15 - 15:00',
        title: 'tokenisation / Tokeny',
        speakers: [],
      },
      {
        type: 'Panel',
        id: 'item-8',
        time: '15:00 - 15:45',
        title: 'Scaling community through different ecosystems',
        speakers: [],
      },
      {
        type: 'Workshop',
        id: 'item-9',
        time: '15:45 - 16:30',
        title: 'Real world assets and DeFi',
        speakers: [],
      },
      {
        id: 'item-11',
        time: '16:30 - 16:45',
        title: 'BREAK',
      },
      {
        type: 'Panel',
        id: 'item-12',
        time: '16:45 - 17:30',
        title: 'DeFi and regulation',
        speakers: [],
      },
      {
        id: 'item-12',
        time: '17:30 - 18:30',
        title: 'Croissant corner',
        speakers: [],
      },
      
    ],
  },
  {
    heading: 'polkadot stage',
    id: 'day-2-2',
    title: 'Day 2 - 19th July',
    showContent: false,
    items: [
      {
        id: 'item-1',
        time: '11:00 - 11:15',
        title: 'Talisman: How Polkadot enables a trailblazing wallet stack.',
        speakers: [],
      },
      {
        id: 'item-2',
        time: '11:15 - 11:30',
        title: 'Taiga Protocol - Unifying Staking Derivatives',
        speakers: [],
      },
      {
        id: 'item-3',
        time: '11:30 - 11:45',
        title: 'TBD',
        speakers: [],
      },
      {
        id: 'item-4',
        time: '11:45 - 12:00',
        title: 'Tellor on Polkadot',
        speakers: [],
      },
      {
        id: 'item-5',
        time: '12:00 - 12:15',
        title: 'Democratizing access to on-chain data',
        speakers: [],
      },
      {
        id: 'item-6',
        time: '12:30 - 12:45',
        title: 'Universal interoperability',
        speakers: [],
      },
      {
        id: 'item-7',
        time: '12:45 - 13:00',
        title: 'Zero-Knowledge Proofs using ink!',
        speakers: [],
      },
      {
        id: 'item-8',
        time: '13:00 - 14:00',
        title: 'LUNCH',
      },
      {
        id: 'item-9',
        time: '14:00 - 14:15',
        title: 'Customizable NFTs',
        speakers: [],
      },
      {
        id: 'item-10',
        time: '14:15 - 14:30',
        title: 'Community Building and Engagement',
        speakers: [],
      },
      {
        id: 'item-11',
        time: '14:30 - 14:45',
        title: 'Liquidity Solutions on Polkadot Parachains & Apps',
        speakers: [],
      },
      {
        id: 'item-12',
        time: '14:45 - 15:00',
        title: 'How we will migrate millions of users to the polkadot ecosystem',
        speakers: [],
      },
      {
        id: 'item-13',
        time: '15:00 - 15:15',
        title: 'Saturn: one multisig, any blockchain.',
        speakers: [],
      },
      {
        id: 'item-14',
        time: '15:15 - 15:30',
        title: 'TBD',
        speakers: [],
      },
      {
        id: 'item-15',
        time: '15:30 - 15:45',
        title: 'WorkFi: The Future of Employment on the Blockchain',
        speakers: [],
      },
      {
        id: 'item-16',
        time: '15:45 - 16:00',
        title: 'TBD',
        speakers: [],
      },
      {
        id: 'item-17',
        time: '16:00 - 16:15',
        title: 'TBD',
        speakers: [],
      },
      {
        id: 'item-18',
        time: '16:15 - 16:30',
        title: 'How do I become a Substrate Developer?',
        speakers: [],
      },
      {
        id: 'item-19',
        time: '16:30 - 18:00',
        title: ' -- ',
      },
      {
        id: 'item-20',
        time: '18:00 - 20:00',
        title: 'Cocktail',
      },
    ],
  },
  {
    heading: 'Rooftop',
    id: 'day-2-3',
    title: 'Day 2 - 19th July',
    showContent: false,
    items: [
      {
        type: "Party with DJ's",
        id: 'item-1',
        time: '18:30 - 22:30',
        title: "DJ Buffalo - D’nis Mongeries <br/>Food and Drinks",
      },
    ],
  },
]

export const day3Program = [
  {
    heading: 'program main stage',
    id: 'day-3-1',
    title: 'Day 3 - 20th July - Interoperability as a mandatory goal',
    showContent: false,
    items: [
      {
        id: 'item-1',
        time: '10:45 - 11:15',
        title: 'Chainsafe Keynote',
        speakers: [],
      },
      {
        id: 'item-2',
        time: '11:15 - 11:45',
        title: 'Horizen Keynote',
        speakers: [],
      },
      {
        id: 'item-3',
        time: '11:45 - 12:15',
        title: 'Near Keynote',
        speakers: [],
      },
      {
        id: 'item-4',
        time: '12:15 - 12:45',
        title: 'Tezos Keynote',
        speakers: [],
      },
      {
        id: 'item-5',
        time: '12:45 - 13:15',
        title: 'Polkadot Keynote',
        speakers: [],
      },
      {
        id: 'item-6',
        time: '13:15 - 14:00',
        title: 'LUNCH',
      },
      {
        id: 'item-7',
        time: '14:00 - 14:30',
        title: 'TBD',
        speakers: [],
      },
      {
        type: 'Panel',
        id: 'item-8',
        time: '14:30 - 15:15',
        title: 'Challenges in Interoperability - DeFi / Users management',
        speakers: [],
      },
      {
        type: 'Panel',
        id: 'item-9',
        time: '15:15 - 16:00',
        title: 'Challenges in Interoperability - Gaming',
        speakers: [],
      },
      {
        id: 'item-10',
        time: '16:00 - 16:10',
        title: 'Closing note',
        speakers: [],
      },
    ],
  },
  {
    heading: 'polkadot stage',
    id: 'day-3-2',
    title: 'Day 3 - 20th July',
    showContent: false,
    items: [
      {
        id: 'item-1',
        time: '11:00 - 11:15',
        title: 'L2 for everything. How to unite all fragmented infrastructure under one roof in a way TCP/IP did it for a bright future of internet where we all lives now',
        speakers: [],
      },
      {
        id: 'item-2',
        time: '11:15 - 11:30',
        title: 'TBD',
        speakers: [],
      },
      {
        id: 'item-3',
        time: '11:30 - 11:45',
        title: 'Dive into Madara : The provable layer for substrate',
        speakers: [],
      },
      {
        id: 'item-4',
        time: '11:45 - 12:00',
        title: 'Multisig wallet: challenges and adoption',
        speakers: [],
      },
      {
        id: 'item-5',
        time: '12:00 - 12:15',
        title: 'Play To Earn is dead, long live Play & Earn!',
        speakers: [],
      },
      {
        id: 'item-6',
        time: '12:00 - 12:45',
        title: 'Panel DeFi DIA',
        speakers: [],
      },
      {
        id: 'item-7',
        time: '12:45 - 13:45',
        title: 'BREAK',
      },
      {
        id: 'item-8',
        time: '13:45 - 14:00',
        title: 'The imperative need to focus on User Acquisition',
        speakers: [],
      },
      {
        id: 'item-9',
        time: '14:00 - 14:15',
        title: 'How to destroy scams with community powered certification',
        speakers: [],
      },
      {
        id: 'item-10',
        time: '14:15 - 14:30',
        title: 'Share the Latam experience boosting the developer ecosystem, connecting with the private sector and empowering communities',
        speakers: [],
      },
      {
        id: 'item-11',
        time: '14:30 - 14:45',
        title: 'TBD',
        speakers: [],
      },
      {
        id: 'item-12',
        time: '14:45 : 15:00',
        title: 'Simulate OpenGov proposals with Chopsticks',
        speakers: [],
      },
    ],
  },
]
